### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by mikine** [alphagov/e-petitions#208]
Hello! This may be a bit dumb question, but still.
When I am switching to the e-petitions project on my server, it gives me the following message:

=> Booting Puma
=> Rails 4.2.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma 2.11.3 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:3000

How and where can I change the settings, so that it runs properly on my server address and not just localhost?

**Comment by oskarpearson** [comment]
Hi

Does this help? It makes the server listen on all IPs:

```shell
... $ bundle exec rails server -b 0.0.0.0
=> Booting Puma
=> Rails 4.2.2 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma 2.11.3 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:3000
```
