### ISSUE TITLE
ALL CAPS TITLES SHOULD BE AVOIDED

### ISSUE THREAD

**Issue by joelanman** [alphagov/e-petitions#339]
https://petition.parliament.uk/petitions/104372

They're ugly and draw attention to petitions that might not warrant it

suggest:

 - automated (but non blocking) warning when user creates petition with high percentage caps
 - automated (but non blocking) warning when admin OKs petition with high percentage caps

**Comment by yahoopete** [comment]
We're working with the moderators to prevent these kinds of titles, so they'll be fixing them prior to publication (in consultation with the petition creator).
