### ISSUE TITLE
Shared "/signatures/" links say "We've added your signature to the petition"

### ISSUE THREAD

**Issue by gwire** [alphagov/e-petitions#341]
A search on twitter shows people are sharing the user-specific "/signatures/" URLs on social media, rather than the intended "/petitions/" link.

* https://twitter.com/search?q=petition.parliament.uk%2Fsignatures%2F&src=typd

Example: https://twitter.com/kerrycumiskey/status/623150244612702208 links to https://petition.parliament.uk/signatures/4688/signed/C6joqh4Feb4SYAWbphCa which returns the message
> "We've added your signature to the petition: To debate a vote of no confidence in Health Secretary the Right Hon Jeremy Hunt"

Which is confusing to a user, since it give the impression that just by following the link they have "signed". Which may not have been their intention.

Also, as an aside I note that this also leaks the signer's constituency, which in some circumstance may be undesirable.

**Comment by yahoopete** [comment]
Thanks @gwire, good spot. We'll find a way to avoid that.

**Comment by henryhadlow** [comment]
Fixed: https://github.com/alphagov/e-petitions/pull/364
