### ISSUE TITLE
signatures_by_country element broken

### ISSUE THREAD

**Issue by matthew-shaw** [alphagov/e-petitions#437]
Since #435 it seems that the `signatures_by_country` element of the json response is either missing or broken. Countries are missing and those that are there have incorrect signature counts.

**Comment by matthew-shaw** [comment]
#436 also refers

**Comment by pixeltrix** [comment]
@matthew-shaw it only includes the new data for the moment until the migration in #436 is run in production. Unfortunately tests have shown that'll take about 35 minutes to complete so we felt that with the interest in the junior doctors strike related petitions it was too risky to run it at the time. Hopefully there will be a quiet time over the weekend and/or some investigations today improve the timings.

Ultimately it will be for the better as now we will be including the ISO code for the countries in the output.

**Comment by pixeltrix** [comment]
@matthew-shaw the old data has been migrated across now - thanks for reporting this.

**Comment by matthew-shaw** [comment]
I'm seeing the ISO country codes, but not the right number of countries or signature counts. Example: https://petition.parliament.uk/petitions/114003.json

**Comment by pixeltrix** [comment]
@matthew-shaw yep, we checked the logs and the `CountryPetitionJournal.reset!` method failed due to an index conflict. The data was migrated successfully from `country` to `location_code` though so I've got a script that will recreate the journals in a more friendly fashion tonight once everyone goes to bed :smile:

**Comment by pixeltrix** [comment]
Script has finished - all the data appears to be there again now.
