### ISSUE TITLE
Too many URLs in Google Analytics

### ISSUE THREAD

**Issue by henryhadlow** [alphagov/e-petitions#448]
because we have the signature ID in the URL

**Comment by pixeltrix** [comment]
Will changing to a query param for the token from it being embedded in the path help fix this? If so that seems like the simplest/cheapest solution.

**Comment by pixeltrix** [comment]
It seems like that could be a solution - see the section "Exclude URL Query Parameters" in this document: https://support.google.com/analytics/answer/1010249?hl=en

**Comment by pixeltrix** [comment]
Also this alert only appears when we have more than 50,000 signatures for a single petition in a day.

**Comment by pixeltrix** [comment]
@henryhadlow PR #467 moves the token to a query param if you want to have a look
