### ISSUE TITLE
Botnet attack

### ISSUE THREAD

**Issue by star-one** [alphagov/e-petitions#499]
Has the site become compromised by a botnet attack, which has circumvented the email confirmation stage?

On the 2nd EU referendum petition the constant trickle of new signatures - including throughout the night - would appear to be suspicious.

**Comment by h-lame** [comment]
Hi @star-one,

No, the site hasn't been compromised - all signatures must go through the email confirmation stage.  The rate of signatures is simply very high.  http://rpubs.com/jefferis/192311 is a good write-up and analysis of the signing rate produced by someone not on the team using our open data.

Hope this answers your questions.
