### ISSUE TITLE
Contacting petitioners

### ISSUE THREAD

**Issue by davidmiller** [alphagov/e-petitions#5]
The benefits of using a petition from http://epetitions.direct.gov.uk/ for one's campaign are manifest. 

Unfortunately, campaigners find themselves subsequently unable to communicate with those people who are manifestly interested in the issue to which the petition pertains.

Would it be possible to add an opt-in "allow $Person_or_organisation" to send me messages about this petition/campaign?

**Comment by henryhadlow** [comment]
This isn't something we're planning to support. We found in user research that people found other petitioning platforms very spammy and this isn't something we want to replicate. It would also require a much larger moderation and support team than we currently operate.
