### ISSUE TITLE
Requires postcode: not all British citizens have a postcode

### ISSUE THREAD

**Issue by wmarshdev** [alphagov/e-petitions#552]
https://petition.parliament.uk/petitions/173199/signatures/new

This UI flow means that British citizens not living in the UK have a choice between not being able to sign, or having to provide a fraudulent postcode.

**Comment by pixeltrix** [comment]
@thegroke the postcode is only required if the country is the UK - [see this line][1].

``` ruby
validates :postcode, presence: true, format: { with: POSTCODE_REGEX }, if: :united_kingdom?
```

[1]: https://github.com/alphagov/e-petitions/blob/9080c2b93adf28dc97f6287174dab7627979074f/app/models/staged/validations/signer_details.rb#L11

**Comment by thegroke** [comment]
I see, my mistake.

I would recommend hiding the postcode field on country selection. Also (this may be my own stupidity) the greyness of the country field made me skip past it, assuming it was disabled or irrelevant.

**Comment by pixeltrix** [comment]
@thegroke thanks for your report - the styling on the website is based on the gov.uk website so we tend to follow their guidelines, but perhaps hiding the postcode like you suggest and using a [type-ahead field][1] for country would be better options. I'll discuss it with the appropriate people.

[1]: https://designpatterns.hackpad.com/Type-ahead-l3OHvWUmDml

**Comment by qaisjp** [comment]
An obvious alternative option would be `disable`ing the postcode input for non-UK countries?
