### ISSUE TITLE
Nginx 502 error when signing petition https://petition.parliament.uk/petitions/241584/

### ISSUE THREAD

**Issue by richardARPANET** [alphagov/e-petitions#681]
When signing this petition https://petition.parliament.uk/petitions/241584/

Submission returns 502 bad gateway on the final page of the process (https://petition.parliament.uk/petitions/241584/signatures/thank-you).

For the sake of the UK please do fix this.

**Comment by Nevexo** [comment]
This is an infrastructure issue, not petitions.

**Comment by richardARPANET** [comment]
It's effecting the customer of the petitions service, so seems a valid issue to me.

**Comment by PaulW** [comment]
No, as mentioned, this will be due to excessive load on the infrastructure.  Depending on how they've got things setup in AWS they can scale up to try and meet demand, I'm not 100% sure whether they're elastic load balancers or what, but sometimes, depending on how it's originally configured, there is only so much you can do, and could take a short time to successfully scale up.

**Comment by richardARPANET** [comment]
![gds](https://user-images.githubusercontent.com/38049750/54769450-17380d00-4bf9-11e9-95d6-658db8d75262.png)

**Comment by JakeMakesStuff** [comment]
This is the source repository for the petitions page, not the page to report infrastructure issues.

**Comment by richardARPANET** [comment]
That's nice @JakeMakesStuff. However I assume they're "agile" at GDS therefore will take **ownership** of their product and keep us updated here.

**Comment by JakeMakesStuff** [comment]
They're keeping people updated [here](https://twitter.com/HoCpetitions).

**Comment by richardARPANET** [comment]
Thanks for the link, take the rest of the day off.

**Comment by lukesmith** [comment]
Looks like they're using [delayed job](https://github.com/collectiveidea/delayed_job) for sending emails async (using the database as the queue).

My guess is the database is under too much load.

So deploy Redis. Swap delayed_job for sidekiq. Relax. 

> Delayed Job uses your SQL database for storage and processes jobs in a single-threaded process. It's simple to set up but the performance and scalability aren't great. I would not use delayed_job for systems processing 100,000s of jobs/day.ttps://github.com/mperham/sidekiq/wiki/FAQ

**Comment by richardARPANET** [comment]
Looks to be resolved now, closing this.
