### ISSUE TITLE
I will just leave this here

### ISSUE THREAD

**Issue by ghost** [alphagov/e-petitions#684]
<img width="1140" alt="Screenshot 2019-03-21 at 15 48 27" src="https://user-images.githubusercontent.com/9044977/54793409-2a1f0180-4c3a-11e9-831b-e750530ff4f1.png">

**Comment by marksteward** [comment]
<img src="http://gif.co/tavW.gif">

**Comment by ooo628616** [comment]
I came across this a while back on Twitter, it creates automated signatures for petitions.

**Comment by pixeltrix** [comment]
The picture is from the 2nd Referendum Petition period in June 2016
