### ISSUE TITLE
How am I supposed to set it up on Ubuntu 18.04 with Docker installed?

### ISSUE THREAD

**Issue by mukberty** [alphagov/e-petitions#766]
I am unable to understand how I have to set it up on a VPS. I have installed Docker. Do I have to clone the repo in a container or something??
Thanks!

**Comment by pixeltrix** [comment]
How did you install docker on Ubuntu 18.04? If you installed via `apt-get` or `aptitude` the version is horribly out-of-date and you should remove it using the following command:

```
$ sudo apt-get remove docker docker-engine docker.io containerd runc docker-compose
```

Then follow the instructions here to install the docker engine:
https://docs.docker.com/engine/install/ubuntu/

Finally, install an up-to-date version of docker-compose by following the instructions for Linux here:
https://docs.docker.com/compose/install/

Once you've done that just clone the repo and run the `docker-compose` commands from inside the root of the project, e.g:

```
$ git clone https://github.com/alphagov/e-petitions.git
$ cd e-petitions
$ docker-compose run --rm web rake db:setup
```

This will give you a working development environment. However, if you're after a production environment then I wouldn't recommend using docker - the easiest solution would be to use Heroku but you won't be able to run it for free.

Can you give a bit more context on what you're trying to do? If you're trying to host your own petition website there maybe other projects more suited to your requirements as this is pretty specific to the UK's parliament and government and would require lots of customisation to remove branding etc.

**Comment by mukberty** [comment]
Cool. Thanks a ton!

**Comment by mukberty** [comment]
Cool. Thanks a ton! 
I am trying to host my own petition site. How do you suggest I go about this.

**Comment by mukberty** [comment]
Cool. Thanks a ton!
I am trying to host my own petition site. How do you suggest I go about this.

**Comment by pixeltrix** [comment]
Who are the site's users? i.e. who is the petitioner, who are the supporters and who are they petitioning? Is it a single petition or is it a petitioning platform like [change.org][3]? What programming languages do you have most experience with?

The code here is designed for members of the public to petition a national government/parliament with set thresholds that trigger actions such as official responses, debates in parliament, etc. We've adapted it a couple of times but they've both been parliaments of some kind - the [States of Jersey][1] and the [Welsh Parliament][2].

[1]: https://petitions.gov.je
[2]: https://petitions.senedd.wales
[3]: https://change.org

**Comment by mukberty** [comment]
It is a petitioning platform like change.org. 
I have most experience with Python3/Flask, but have worked with PHP and HTML(with both NGINX and Apache).

**Comment by pixeltrix** [comment]
In that case I'd suggest focussing on [Pytition][1], which I can see you've found - it's Django and not Flask but at least it's not Ruby on Rails like this repo is.

[1]: https://github.com/pytition/Pytition
