### ISSUE TITLE
Sending emails with SMTP

### ISSUE THREAD

**Issue by IsGabriellaCurious** [alphagov/e-petitions#813]
Hey!

I've been trying to send emails with a different SMTP server compared to the usual mailcatcher. I've changed the usual config in the `development.rb` env config to remove the if statement and just have:

```
    config.action_mailer.delivery_method = :smtp
    config.action_mailer.smtp_settings = {
      address: ENV.fetch('SMTP_HOST'),
      port: ENV.fetch('SMTP_PORT'),
      username: ENV.fetch('SMTP_USERNAME'),
      password: ENV.fetch('SMTP_PASSWORD'),
      authentication: 'login',
      enable_starttls_auto: true
    }
```

All the variables have been written out in both `.env.development` and `docker-compose.yml`. However, when something happens that's meant to send an email nothing gets received. I've tested the SMTP details and everything and it works fine, just nothing is sending from here? Is it even possible to do this?

Help would be appreciated 😄

**Comment by pixeltrix** [comment]
The emails are sent in background jobs like [EmailConfirmationForSignerEmailJob][1] - are you running the worker process and if so can you see the jobs being performed in the logs? It sounds like the jobs are sitting in the Delayed Job queue which can be accessed at http://localhost:3000/admin/delayed/jobs once you've created an admin user and signed in.

[1]: https://github.com/alphagov/e-petitions/blob/master/app/jobs/email_confirmation_for_signer_email_job.rb

**Comment by IsGabriellaCurious** [comment]
Thank you for that link - I've had a look and it's giving me a `SMTP-AUTH requested but missing user name` error. So it looks like its an issue on my end. I never got any logs from the worker from docker, so this is very helpful. I'll post an update if I get it working, I'll have a look into it :)

Thanks for your help

**Comment by IsGabriellaCurious** [comment]
And got it! The correct param is `user_name`

Thanks for your help 😄
