### ISSUE TITLE
Update crown image

### ISSUE THREAD

**Issue by matteason** [alphagov/e-petitions#878]
Just a heads up, in case you weren't already aware, that the GOV.UK crown is being updated soon to match the new royal cypher: https://github.com/alphagov/govuk-frontend/issues/4058

Petitions uses the crown in several places, eg on government responses: https://petition.parliament.uk/petitions/636546?reveal_response=yes#response-threshold

Affected images are:

https://github.com/alphagov/e-petitions/blob/master/app/assets/images/graphics/graphic_crown.png
https://github.com/alphagov/e-petitions/blob/master/app/assets/images/graphics/graphic_crown-white.png
https://github.com/alphagov/e-petitions/blob/master/app/assets/images/graphics/graphic_crown-2x.png
https://github.com/alphagov/e-petitions/blob/master/app/assets/images/graphics/graphic_crown-white-2x.png

**Comment by pixeltrix** [comment]
@matteason thanks for the heads up - will let the Parliament team know about it.

**Comment by pixeltrix** [comment]
@matteason I assume we'll need to update the coat of arms in the footer as well at some point but we're waiting on the College of Arms to prepare the new rendering?

**Comment by matteason** [comment]
@pixeltrix Afraid I'm not sure what's happening with the coat of arms - it's been asked about here: https://github.com/alphagov/govuk-frontend/issues/4019#issuecomment-1682181466

I assume that's going to be a more drawn-out process since the coat of arms is more complicated visually and it's featured in (most) departmental logos too, which will all need updating

**Comment by pixeltrix** [comment]
Closed by #1038
